project:
  type: book

book:
  title: "Introduction aux grappes de calcul - Alliance de Recherche Numérique du Canada"
  author: "CCJ, VC, VB"
  date: "2024-01-04"
  chapters:
    - index.qmd
    - 1_Intro.qmd
    - 2_Synthese_concepts_base.qmd
    - 3_Pre-requis.qmd
    - 4_Workflow.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    # theme: cosmo
    theme: flatly
    # theme: minty
    # theme: quartz


  pdf:
    documentclass: scrreprt